base: 'https://typo3-bugs.ddev.site/'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
    hreflang: ''
    websiteTitle: ''
  -
    title: German
    enabled: true
    locale: de_DE
    hreflang: ''
    base: /de/
    websiteTitle: ''
    navigationTitle: Deutsch
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: 1
  -
    title: French
    enabled: true
    locale: fr_FR
    hreflang: ''
    base: /fr/
    websiteTitle: ''
    navigationTitle: Français
    fallbackType: strict
    fallbacks: ''
    flag: fr
    languageId: 2
rootPageId: 1
websiteTitle: ''
